# ===== Prefix tusu: Ctrl+b yerine Ctrl+f =====
unbind C-b
set -g prefix C-f
bind C-f send-prefix          # iki kez Ctrl+f -> alttaki uygulamaya iletir

# ===== Alt bar (status bar) renkleri =====
set -g status-style "bg=black,fg=white"

# ===== Split (bolme) tuslari =====
# "  -> yan yana (sol/sag)
unbind '"'
bind '"' split-window -h

# %  -> alt alta (ust/alt)
unbind %
bind % split-window -v
