# ┌──────────────────────────────┐
# │                              │
# │     ░█░█░▀█▀░▀█▀░▀█▀░█░█     │
# │     ░█▀▄░░█░░░█░░░█░░░█░     │
# │     ░▀░▀░▀▀▀░░▀░░░▀░░░▀░     │
# │                              │
# └──────────────────────────────┘

background_opacity 0.80
allow_remote_control yes
dynamic_background_opacity yes

font_size	 11
# modify_font cell_height 90%

remember_window_size  no
initial_window_width  1000
initial_window_height 500
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
scrollback_lines 10000
enable_audio_bell no

window_padding_width 5

hide_window_decorations yes

confirm_os_window_close 0

cursor_trail 1
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

map ctrl+t new_tab
map ctrl+w close_tab

map ctrl+z send_text all \x03
