[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.95
blur = true
[colors.primary]
background = "#000000"
foreground = "#c0caf5"

[keyboard]
bindings = [
  # Ctrl+C -> Copy
  { key = "C", mods = "Control", action = "Copy" },

  # Ctrl+V -> Paste
  { key = "V", mods = "Control", action = "Paste" },

  # Ctrl+Z -> Send SIGINT (eski Ctrl+C davranışı)
  { key = "Z", mods = "Control", chars = "\u0003" }
]
